Cyber_Kitchen/Controllers/DataUploadController.cs
using Cyber_Kitchen.Interface;
using Cyber_Kitchen.Interface.Utils;
using Cyber_Kitchen.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace Cyber_Kitchen.Controllers
{
   
    public class DataUploadController : Controller
    {
       
        private IUploadManager _uploadMgr;
        private IVoterManager _votMgr;
        private IExcelProcessor _excel;
        private ApplicationUserManager _userManager;
        public DataUploadController(ApplicationUserManager userManager, IUploadManager uploadMgr, IVoterManager votMgr, IExcelProcessor excel)
        {
            _uploadMgr = uploadMgr;
            _votMgr = votMgr;
            _excel = excel;
            _userManager = userManager;
          
        }
        //public async Task<ActionResult> Users(Stream stream, UserModel model)
        //{
           
        //        var shts = _excel.Load<UserModel>(stream);

        //        foreach (var row in shts)
        //        {
        //            var userModel = new UserModel
        //            {
        //                UserName = row.UserName,
        //                Password = "open"
        //            };
                  
        //              if (!string.IsNullOrEmpty(userModel.UserName))
        //            {
                                    
        //            var user = new ApplicationUser
        //               { UserName = userModel.UserName,
        //                 PasswordHash = userModel.Password
        //               };

        //             var result = await UserManager.CreateAsync(user, user.Password);
                   

        //            //if  user creation is successful
        //            if (result.Succeeded)
        //            {
        //                // create user role "User"
        //                var addRole = await UserManager.AddToRoleAsync(user.Id, "User");
        //            }
                                       
        //        }

        //    }

        //    return View(model);
           
        //}
        // GET: DataUpload
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult VoterNames()
        {
            CheckTempData();
            DropDown();
            var model = new VoterModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult VoterNames(HttpPostedFileBase file, VoterModel model)
        {
            DropDown();
            if (file != null && file.ContentLength != 0 && (System.IO.Path.GetExtension(file.FileName).ToLower() == ".xlsx" || System.IO.Path.GetExtension(file.FileName).ToLower() == ".xls"))
            {
                model.CreatedBy = User.Identity.GetUserName();
                model.ModifiedBy = User.Identity.GetUserName();
                var uploadedResult = _uploadMgr.UploadStaffNames(file.InputStream, model);

                if (uploadedResult.Succeeded == false)
                {
                    ViewBag.Error = $"{uploadedResult.Message}";
                    ModelState.AddModelError(string.Empty, uploadedResult.Message);
                    return View(model);
                }
                //TempData["message"] = new ResponseModel { Success = $"Voter Names was successfully Uploaded!", Error = "" };
                //return RedirectToAction("AdmittedStudents");
            }
            ModelState.AddModelError(string.Empty, "Only Excel Sheets are allowed");
            return View(model);
        }
        private void DropDown()
        {
            ViewBag.voters = new SelectList(_votMgr.GetVoters().Result, "VoterId", "StaffName");

        }
        private void CheckTempData()
        {
            if (TempData["message"] != null)
            {
                var responseModel = (ResponseModel)TempData["message"];
                ViewBag.Success = !string.IsNullOrEmpty(responseModel.Success) ? responseModel.Success : "";
                ViewBag.Error = !string.IsNullOrEmpty(responseModel.Error) ? responseModel.Error : "";
                ModelState.AddModelError(string.Empty, !string.IsNullOrEmpty(responseModel.Success) ? responseModel.Success : responseModel.Error);
            }
            TempData["message"] = null;
        }
        public ActionResult DownloadStaffNameTemplate()
        {
            return Redirect("~/DataUploadTemplates/StaffNamesample.xlsx");
        }

    }
}

Cyber_Kitchen/Views/DataUpload/VoterNames.cshtml
@model Cyber_Kitchen.Models.VoterModel

@{
    ViewBag.Title = "Upload Voter Names";

}

<div class="page-content-wrapper">
    @*@Html.Partial("Message")*@
    <div class="page-content" style="min-height:1603px">
        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class="pull-left">
                    <div class="page-title">Upload Staff Names</div>
                </div>
                @*<ol class="breadcrumb page-breadcrumb pull-right">
                    <li>
                        <i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="index.html">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a class="parent-item" href="#">Student</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li class="active">Upload Voter Names</li>
                </ol>*@
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="card card-box">
                    @*<div class="card-head">
                        <header>Basic Information</header>
                        <button id="panel-button" class="mdl-button mdl-js-button mdl-button--icon pull-right" data-upgraded=",MaterialButton">
                            <i class="material-icons">more_vert</i>
                        </button>
                      
                    </div>*@
                    <div class="card-body" id="bar-parent">
                        <form action="VoterNames" method="Post" id="form_sample_1" class="form-horizontal" novalidate="novalidate" enctype="multipart/form-data">
                            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                            <div class="form-body">
                                @*<div class="form-group row">
                                    <label class="control-label col-md-3">
                                        Voter Names
                                        <span class="required" aria-required="true"> * </span>
                                    </label>
                                    <div class="col-md-5">

                                        @Html.DropDownListFor(m => m.VoterId, (IEnumerable<SelectListItem>)ViewBag.voters, " select your name", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.VoterId, "", new { @class = "text-danger" })
                                  </div>
                                </div>*@
                                

                                <div class="form-actions">
                                    <div class="row">
                                        <div class="offset-md-3 col-md-3">
                                            <input type="file" accept="application/vnd.ms-excel" name="file" id="file" />
                                            <button type="submit" class="btn btn-info" id="submitData">Upload</button>
                                        </div>
                                        <div class="col-md-1">
                                            @*@Html.ActionLink("Download Template", "DownloadVoterTemplate", "DataUpload")*@
                                            @Html.ActionLink("Download Template", "DownloadStaffNamesample", "DataUpload")
                                            @*<a href="/DataUploadTemplates/StaffNamesample.xlsx" download="">Download Template</a>*@
                                           
                                        </div>
                                    </div>                                         
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Script{
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/toastr.js"></script>

    <script type="text/javascript">toastr.success("@(TempData["Message"] as string)");</script>
}