Cyber_Kitchen/Entities/Score.cs
using Cyber_Kitchen.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cyber_Kitchen.Entities
{
    public partial class Score
    {
        public int ScoreId { get; set; }
        public int? VoterId { get; set; }
        public int? RestId { get; set; }
        public string UserId { get; set; }
        public int Taste { get; set; }
        public int Quality { get; set; }
        public int Quantity { get; set; }
        public int TimeLiness { get; set; }
        public int CustomerServices { get; set; }
        public decimal TotalScore { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }

        public virtual Voter Voter { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

Cyber_Kitchen/Controllers/ScoreController.cs
using Cyber_Kitchen.Entities;
using Cyber_Kitchen.Interface;
using Cyber_Kitchen.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cyber_Kitchen.Controllers
{
    //[Authorize]
    public class ScoreController : Controller
    {
        private IScoreManager _scoreMgr;
        private IVoterManager _votMgr;
        private IRestaurantManager _restMgr;

        public ScoreController(IScoreManager scoreMgr, IVoterManager votMgr, IRestaurantManager restMgr)
        {
            _scoreMgr = scoreMgr;
            _votMgr = votMgr;
            _restMgr = restMgr;
        }

        //GET: Score
        public ActionResult Index()
        {
            if (TempData["message"] != null)
            {
                ViewBag.Success = (string)TempData["message"];
            }
            var results = _scoreMgr.GetScores();

            if (results.Succeeded == true)
            {
                List<Score> mylist = new List<Score>();

                foreach (var item in results.Unwrap())
                {
                    item.TotalScore =
                        item.Quality + item.Quantity + item.Taste + item.CustomerServices + item.TimeLiness;
                }
                return View(results.Unwrap());
            }

            else
            {
                ModelState.AddModelError(string.Empty, "An error occure");
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            var results = _scoreMgr.GetScoreById(id);
            return View(results);
        }

        [HttpGet]
        public ActionResult CreateScore()
        {
            ViewBag.voters = new SelectList(_votMgr.GetVoters().Result, "VoterId", "StaffName");
            ViewBag.restaurants = new SelectList(_restMgr.GetRestaurants().Result, "RestId", "RestName");

            return View();
        }

        //[HttpPost]

        //public ActionResult CreateScore(ScoreModel model)
        //{
        //    var userId = User.Identity.GetUserId();
        //    ViewBag.voters = new SelectList(_votMgr.GetVoters().Result, "VoterId", "StaffName");
        //    ViewBag.restaurants = new SelectList(_restMgr.GetRestaurants().Result, "RestId", "RestName");

        //    model.UserId = userId;  // This  enable you to track or validate the user login Id to ovid multiple voting. first , add UserId to Voter Table
        //    model.CreatedBy = User.Identity.GetUserName();
        //    var result = _scoreMgr.CreateScore(model);
        //    if (result.Succeeded == true)
        //    {
        //        TempData["message"] = $"Score{model.ScoreId} was successfully added!";

        //        if (User.IsInRole("Admin"))
        //        {
        //            return RedirectToAction("Index");
        //        }
        //        return RedirectToAction("Index", "Home");


        //    }
        //    return View(model);
        //}

        [HttpGet]
        public ActionResult EditScore(int id = 0)
        {
            var result = _scoreMgr.GetScoreById(id);
            if (result.Succeeded == true)
            {
                return View(result.Result);
            }
            else
            {
                ModelState.AddModelError(string.Empty, result.Message);
                return View();
            }
        }
        [HttpPost]
        public ActionResult EditScore(ScoreModel model)
        {

            if (ModelState.IsValid)
            {
                model.ModifiedBy = User.Identity.GetUserId();
                var result = _scoreMgr.UpdateScore(model);
                if (result.Succeeded == true)
                {
                    TempData["message"] = $"Score{model.ScoreId} was successfully added!";
                    ModelState.AddModelError(string.Empty, "Update was successfully ");
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, result.Message);
                ViewBag.Error = $"Error occured : {result.Message}";
                return View(model);
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult DeleteScore(int id)
        {
            var result = _scoreMgr.GetScoreById(id);
            if (result.Succeeded)
            {
                return View(result.Result);
            }
            else
            {
                ModelState.AddModelError(string.Empty, result.Message);
                return View();
            }
        }

        [HttpPost]
        public ActionResult DeleteScore(int id, Score model)
        {
            var result = _scoreMgr.GetScoreById(id);
            if (result == null)
            {
                return View("not found");
            }
            _scoreMgr.DeleteScore(id);
            return RedirectToAction("Index");


        }

    }
}

Cyber_Kitchen/Views/Score/CreateScore.cshtml
@model Cyber_Kitchen.Models.ScoreModel

@{
    ViewBag.Title = "CreateScore";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="alert-info">CHOOSE YOUR CHOICE TO SUIT THE BEST CATERER</h1>
<ol class="breadcrumb page-breadcrumb pull-right">

</ol>
@*<p>
    @Html.ActionLink("New Catere", "CreateRestaurant", "Restaurant", null, new { @class = "btn btn-primary" })
</p>*@
<div class="card-body" id="bar-parent">
    <form action="CreateScore" method="Post" id="form_sample_1" class="form-horizontal" novalidate="novalidate">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-body">
            @*<div class="form-group row">
                <label class="control-label col-md-3">
                    Voter Name
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">
                    @Html.DropDownListFor(m => m.VoterId, (IEnumerable<SelectListItem>)ViewBag.voters, " select your name", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.VoterId, "", new { @class = "text-danger" })
                    @Html.HiddenFor(m => m.VoterId)

                </div>
                </div>*@
            @*@Html.TextBoxFor(u =>u.UserId)*@
            @Html.HiddenFor(u =>u.UserId)
            @Html.ValidationMessageFor(u => u.UserId, "", new { @class = "text-danger" })
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Restaurant Name
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">
                    @Html.DropDownListFor(m => m.RestId, (IEnumerable<SelectListItem>)ViewBag.restaurants," select your caterer", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.RestId, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Taste
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">

                    <select id="taste" name="Taste" class="form-control">
                        <option value="">select</option>
                        <option value="1">Very Bad</option>
                        <option value="2">Bad</option>
                        <option value="3">Neutral</option>
                        <option value="4">Good</option>
                        <option value="5">Excelent</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Quality
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">

                    <select id="quality"name="Quality"class="form-control">
                        <option value="">select</option>
                        <option value="1">Very Bad</option>
                        <option value="2">Bad</option>
                        <option value="3">Neutral</option>
                        <option value="4">Good</option>
                        <option value="5">Excelent</option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-md-3">
                    Quantity
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">

                    <select id="quantity" name="Quantity"class="form-control">
                        <option value="">select</option>
                        <option value="1">Very Bad</option>
                        <option value="2">Bad</option>
                        <option value="3">Neutral</option>
                        <option value="4">Good</option>
                        <option value="5">Excelent</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    TimeLiness
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">

                    <select id="timeliness" name="TimeLiness"class="form-control">
                        <option value="">select</option>
                        <option value="1">Very Bad</option>
                        <option value="2">Bad</option>
                        <option value="3">Neutral</option>
                        <option value="4">Good</option>
                        <option value="5">Excelent</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    CustomerServices
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">

                    <select id="customerServices" name="CustomerServices"class="form-control">
                        <option value="">select</option>
                        <option value="1">Very Bad</option>
                        <option value="2">Bad</option>
                        <option value="3">Neutral</option>
                        <option value="4">Good</option>
                        <option value="5">Excelent</option>
                    </select>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="offset-md-3 col-md-6 pull-right">
                        <button type="submit" class="btn btn-info" id="submitData">Save</button>
                        <button type="button" class="btn btn-danger">Cancel</button>

                    </div>
                    <div class=" col-md-1">
                        <a href="@Url.Action("Index","Score", new { area = ""})" class="btn btn-chatpane">Back To List(s)</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>



    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Cyber_Kitchen/Views/Score/DeleteScore.cshtml
@model Cyber_Kitchen.Models.ScoreModel

@{
    ViewBag.Title = "DeleteScore";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ScoreId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScoreId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VoterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VoterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RestId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RestId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Taste)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Taste)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeLiness)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeLiness)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerServices)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerServices)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalScore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>


@*@section scripts
        {
    <script>
                $(document).ready(function () {
                    $(".js-delete-score").click(function (e)
                    {
                        var link = $(e.target);

                        if (confirm("Are you sure you want to delete this score")) {
                            $.ajax({
                                url: "/api/score/" + link.attr("data-score-id"),
                                method: "DELETE"
                            })
                            .done(function () {
                                link.parents("li").fadeOut(function () {
                                    $(this).remove();
                                });
                            })
                            .fail(function () {
                                alert("Something failed!");
                            });
                        }
                    });
                });
    </script>
}
<a href="/Score/DeleteScore/7" class="js-delete-score">Delete</a>*@

Cyber_Kitchen/Views/Score/Details.cshtml
@model Cyber_Kitchen.Models.ScoreModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ScoreModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ScoreId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScoreId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VoterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VoterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RestId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RestId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Taste)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Taste)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeLiness)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeLiness)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerServices)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerServices)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalScore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Cyber_Kitchen/Views/Score/Index.cshtml
@model IEnumerable<Cyber_Kitchen.Models.ScoreModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <ol class="breadcrumb page-breadcrumb pull-right">
    </ol>
</div>

<h1 class="alert-info">DETAILS OF EACH VOTING</h1>
<div class="btn-group">
    @if (User.IsInRole("Admin"))
    {
        <a href="@Url.Action("CreateScore", "Score")" class="btn btn-info "><i class="fa fa-plus"></i>Add New </a>
    }
   
</div>

<div">
    <table class="table table-striped table-bordered table-hover ">
        <thead>
            <tr>
                @if (User.IsInRole("Admin"))
                {
                    <th> Score Id </th>
                }
              
                @*<th> @Html.LabelFor(m => m.FirstOrDefault().VoterId) </th>*@
                <th> @Html.LabelFor(m => m.FirstOrDefault().RestId) </th>
                <th> Taste  </th>
                <th> Quality </th>
                <th> Quantity</th>
                <th> TimeLiness </th>
                <th>CustomerServices</th>
                <th> TotalScore</th>
              
                @if (User.IsInRole("Admin"))
                {
                    <th> Date Created </th>
                    <th> Action </th>
                }
               
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="gradeX odd" role="row" id="row-@item.ScoreId">

                    @if (User.IsInRole("Admin"))
                    {
                        <td class="left">@Html.DisplayFor(modelItem => item.ScoreId)</td>
                    }
                    
                    @*<td>@Html.DisplayFor(modelItem => item.Voters.VotName)</td>*@
                    <td>@Html.DisplayFor(modelItem => item.Restaurant.RestName)</td>
                    <td>@Html.DisplayFor(modelItem => item.Taste)</td>
                    <td>@Html.DisplayFor(modelItem => item.Quality)</td>
                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                    <td>@Html.DisplayFor(modelItem => item.TimeLiness)</td>
                    <td>@Html.DisplayFor(modelItem => item.CustomerServices)</td>
                    <td>@Html.DisplayFor(modelItem => item.TotalScore)</td>
                    @if (User.IsInRole("Admin"))
                    {
                        <td>@String.Format("{0:d}", item.CreatedDate)</td>
                    }
                        @if (User.IsInRole("Admin"))
                        {
                            <td>
                                <a href="/Score/DeleteScore?id=@item.ScoreId" class="btn btn-danger btn-xs" id="deleteaction" data-id="@item.ScoreId" data-name="@item.ScoreId">
                                    <i class="fa fa-trash-o "></i>
                                </a>
                                @*<a href="/Score/DeleteScore?id=@item.ScoreId" class="js-delete-score" data-score-id="@item.ScoreId">Delete</a>*@
                                @*<a href="/Score/DeleteScore/7" class="js-delete-score">Delete</a>*@

                            </td>
                        } 
                </tr>
            }

        </tbody>
    </table>
   

    @*@section scripts
        {
            <script>
                $(document).ready(function () {
                    $(".js-delete-score").click(function (e)
                    {
                        var link = $(e.target);

                        if (confirm("Are you sure you want to delete this score")) {
                            $.ajax({
                                url: "/api/score/" + link.attr("data-score-id"),
                                method: "DELETE"
                            })
                            .done(function () {
                                link.parents("li").fadeOut(function () {
                                    $(this).remove();
                                });
                            })
                            .fail(function () {
                                alert("Something failed!");
                            });
                        }
                    });
                });
            </script>
          }*@
    @*<a href="/Score/DeleteScore/7" class="delete">Delete</a>*@