Cyber_Kitchen/Entities/Voter.cs
using Cyber_Kitchen.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cyber_Kitchen.Entities
{
  
        public partial class Voter
        {
            public int VoterId { get; set; }
        public string UserId { get; set; }
        public string StaffName { get; set; }
            public string Email { get; set; }
            public string StaffNo { get; set; }
        public string Department { get; set; }
        public string CreatedBy { get; set; }
            public DateTime CreatedDate { get; set; }
            public string ModifiedBy { get; set; }
            public DateTime ModifiedDate { get; set; }
            //public bool isPasswordChanged { get; set; }

            public virtual ApplicationUser User { get; set; }
    }
}

Cyber_Kitchen/Controllers/VoterController.cs
using Cyber_Kitchen.Entities;
using Cyber_Kitchen.Interface;
using Cyber_Kitchen.Interface.Utils;
using Cyber_Kitchen.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using Remotion.FunctionalProgramming;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cyber_Kitchen.Controllers
{
    [Authorize]
    public class VoterController : Controller
    {
        private IVoterManager _votMgr;
        private IExcelProcessor _excel;
       // private readonly UserManager<ApplicationUser> _applicationUser;
        public VoterController(IVoterManager votMgr,IExcelProcessor excel)
        {
            _votMgr = votMgr;
            _excel = excel;
            //_applicationUser = user;
        }

        // GET: Restaurant
        public ActionResult Index(int? page, string searchBy, string search)
        {
            if (TempData["message"] != null)
            {
                ViewBag.Success = (string)TempData["message"];
            }
          
         
          var results = _votMgr.GetVoters();

            if (searchBy == "StaffName")
            {
                //
                var returnResult = results.Result.Where(x => x.StaffName.ToLower().Contains(search.ToLower())).ToPagedList(page ?? 1, 12);
                return View(returnResult);

            }

            if (results.Succeeded == true)
            {
                ////ADDED ARRANGE NAMES ALPHABETICAL ORDER
                  return View(results.Unwrap().OrderBy(c => c.StaffName).ToPagedList(page ?? 1, 12));
              //  return View(results.Unwrap().OrderBy(c => c.StaffName).ToPagedList(page ?? 1, 12));
            }
           
            else
            {
                ModelState.AddModelError(string.Empty, "An error occure");
                return View(results.Unwrap().ToPagedList(page ?? 1, 12));
            }
         

        }
        [HttpGet]
        public ActionResult CreateVoter()
        {

            return View();
        }
        [HttpPost]
       
        public ActionResult CreateVoter(VoterModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.CreatedBy = User.Identity.GetUserName();
                    //model.Email = User.Identity.GetUserName();
                    //model.StaffNo = User.Identity.GetUserId();
                    var result = _votMgr.CreateVoter(model);
                    if (result.Succeeded == true)
                    {
                        TempData["message"] = $"Voter{model.StaffName} was successfully added!";
                        return RedirectToAction("Index");
                    }
                }
                     catch(Exception ex)
                {
                    throw ex;
                }
            }
           
            return View(model);
        }
        [HttpGet]
        public ActionResult EditVoter(int id = 0)
        {
            var result = _votMgr.GetVoterById(id);
            if (result.Succeeded)
            {
                return View(result.Result);
            }
            else
            {
                ModelState.AddModelError(string.Empty, result.Message);
                return View();

            }
        }
        [HttpPost]
        public ActionResult EditVoter(VoterModel model)
        {
            if (ModelState.IsValid)
            {
                model.ModifiedBy = User.Identity.GetUserName();
                var result = _votMgr.UpdateVoter(model);
                if (result.Succeeded)
                {
                    TempData["message"] = $"Voter{model.StaffName} was successfully added!";
                    ModelState.AddModelError(string.Empty, "Update was successfully ");
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, result.Message);
                    return View(model);

                }
            }
            return View(model);
        }
        //[HttpGet]
        //public ActionResult DeleteVoter(int id)
        //{
        //    var result = _votMgr.GetVoterById(id);
        //    if (result.Succeeded)
        //    {
        //        return View(result.Result);
        //    }
        //    else
        //    {
        //        ModelState.AddModelError(string.Empty, result.Message);
        //        return View();
        //    }
        //}

        [HttpPost]
        public JsonResult DeleteVoter(int id, string votName)
        {
            int votId = Convert.ToInt32(id);
            if (votId > 0)
            {
                var result = _votMgr.DeleteVoter(votId);
                if (result.Succeeded == true)
                {

                    return Json(new { status = true, message = $" {votName} has been successfully deleted!", JsonRequestBehavior.AllowGet });
                }
                return Json(new { status = false, error = result.Message }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { status = false, error = "Invalid Id" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult UploadVoters()
        {
            DropDown();
            var model = new VoterModel();
            return View(model);
        } 
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult UploadVoters(HttpPostedFileBase file, VoterModel model)
        {
            DropDown();
            try
            {
                if (file != null && file.ContentLength != 0 && (System.IO.Path.GetExtension(file.FileName).ToLower() == ".xlsx" || System.IO.Path.GetExtension(file.FileName).ToLower() == ".xls"))
                {
                    model.CreatedBy = User.Identity.GetUserName();
                    model.ModifiedBy = User.Identity.GetUserName();
                    var uploadedResult = _votMgr.UploadVoterNames(file.InputStream, model);
                    if (uploadedResult.Succeeded == true)
                    {

                        TempData["message"] = $"  Voter was successfully Uploaded!";
                        return RedirectToAction("Index");
                    }
                    
                    //else
                    //{
                    //    ModelState.AddModelError(string.Empty, uploadedResult.Message);
                    //    ViewBag.Error = $"Error occured : {uploadedResult.Message}";
                    //    return View(model);
                    //}
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            //else
            //{
            //    ViewBag.Error = "Only Excel Sheets are allowed";
            //}
            //}
            return View();
        }
        private void DropDown()
        {
            ViewBag.voters = new SelectList(_votMgr.GetVoters().Result, "VoterId", "StaffName");
        }

        public ActionResult DownloadStaffTemplate()
        {
            //return Redirect("~/DataUploadTemplates/VoterNamesample.xls");
            return Redirect("~/DataUploadTemplates/StaffNamesample.xlsx");

        }

        
    }
}

Cyber_Kitchen/Views/Voter/CreateVoter.cshtml
@model Cyber_Kitchen.Models.VoterModel

@{
    ViewBag.Title = "CreateVoter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb page-breadcrumb pull-right">
    @*<li>
        <i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="index.html">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
    </li>
    <li>
        <a class="parent-item" href="index">Voter</a>&nbsp;<i class="fa fa-angle-right"></i>
    </li>*@

</ol>
<h1 class="alert-info">ADD STAFF</h1>
<div class="card-body" id="bar-parent">
    <form action="CreateVoter" method="Post" id="form_sample_1" class="form-horizontal">
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-body">
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Staff Name
                    <span @*class="required" aria-required="true"*@> *</span>
                </label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.StaffName, new { @class = "form-control input-height", placeholder = "enter staff name" })
                    @Html.ValidationMessageFor(m => m.StaffName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Staff No.
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.StaffNo, new { @class = "form-control input-height", placeholder = "enter staff no" })
                    @Html.ValidationMessageFor(m => m.StaffNo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Department
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.Department, new { @class = "form-control input-height", placeholder = "enter staff email" })
                    @Html.ValidationMessageFor(m => m.Department, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Email
                    <span class="required" aria-required="true"> * </span>
                </label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control input-height", placeholder = "enter staff email" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="offset-md-3 col-md-6 pull-right" >
                        <button type="submit" class="btn btn-info" id="submitData">Save</button>
                        @*<button type="button" class="btn btn-danger">Cancel</button>*@

                    </div>
                  
                </div>
            </div>
            @*<div class="form-actions">
                <div class="row">
                    <div class="offset-md-2 col-md-2">
                        <input type="file" accept="application/vnd.ms-excel" name="file" id="file" />
                        <button type="submit" class="btn btn-info" id="submitData">Upload</button>
                    </div>
                    <div class="col-md-1">
                        @*<a href="~/DataUploadTemplates/StaffNamesample.xlsx" download="">Download Template</a>*@

                        @*@Html.ActionLink("Download Template", "DownloadStaffTemplate", "Voter")

                    </div>
                </div>
            </div>*@
            <div class=" col-md-1">
                <a href="@Url.Action("Index","Voter", new { area = ""})" class="btn btn-chatpane">Back To List(s)</a>
            </div>
        </div>
    </form>
</div>






@*@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
        @*<div class="form-group">
            @Html.LabelFor(model => model.VoterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VoterId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VoterId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.VotName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VotName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VotName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StaffNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StaffNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StaffNo, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}*@

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
<link href="~/Content/toastr.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.0.0.js"></script>
<script src="~/Scripts/toastr.js"></script>

<script type="text/javascript">toastr.success("@(TempData["Message"] as string)");</script>
    @Scripts.Render("~/bundles/jqueryval")
}

Cyber_Kitchen/Views/Voter/DeleteVoter.cshtml
@model Cyber_Kitchen.Models.VoterModel

@{
    ViewBag.Title = "DeleteVoter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VoterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VoterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StaffName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StaffName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StaffNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StaffNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Cyber_Kitchen/Views/Voter/EditVoter.cshtml
@model Cyber_Kitchen.Models.VoterModel

@{
    ViewBag.Title = "EditVoter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="alert-info">EDIT VOTER</h1>
<div class="card-body" id="bar-parent">
    <form action="EditVoter" method="Post" id="form_sample_1" class="form-horizontal" >
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-body">
            <input type="hidden" name="VoterId" value="@Model.VoterId" />
           
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Voter Name
                    <span ></span>
                </label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.StaffName, new { @class = "form-control input-height", placeholder = "enter voter name" })
                    @Html.ValidationMessageFor(m => m.StaffName, "", new { @class = "text-danger" })
                    @*@Html.HiddenFor(model => model.VoterId, new { htmlAttributes = new { @class = "form-control" } })*@
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Staff No.
                    <span> </span>
                </label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.StaffNo, new { @class = "form-control input-height", placeholder = "enter staffno name" })
                    @Html.ValidationMessageFor(m => m.StaffNo, "", new { @class = "text-danger" })
                    @*@Html.HiddenFor(model => model.VoterId, new { htmlAttributes = new { @class = "form-control" } })*@
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Department
                    <span></span>
                </label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.Department, new { @class = "form-control input-height", placeholder = "enter staffno name" })
                    @Html.ValidationMessageFor(m => m.Department, "", new { @class = "text-danger" })
                    @*@Html.HiddenFor(model => model.VoterId, new { htmlAttributes = new { @class = "form-control" } })*@
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-md-3">
                    Email
                    <span></span>
                </label>
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control input-height", placeholder = "enter staffno name" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    @*@Html.HiddenFor(model => model.VoterId, new { htmlAttributes = new { @class = "form-control" } })*@
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="offset-md-3 col-md-6 pull-right">
                        <button type="submit" class="btn btn-info" id="submitData">Save</button>
                        @*<button type="button" class="btn btn-default">Cancel</button>*@
                    </div>
                </div>
            </div>
            <div class=" col-md-1">
                <a href="@Url.Action("Index","Voter", new { area = "" })" class="btn btn-chatpane">Back To List(s)</a>
            </div>
        </div>

    </form>
</div>

Cyber_Kitchen/Views/Voter/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<Cyber_Kitchen.Models.VoterModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int ratingPeriod = 0;
    ratingPeriod = Convert.ToInt32(ViewBag.Period);
}


<h1></h1>
<h1></h1>
<h1></h1>
<h1></h1>

<h1></h1>


<p class="btn-default pull-right">
    @using (Html.BeginForm("Index", "Voter", FormMethod.Get))
    {
        if (User.IsInRole("Admin"))
        { 
            @Html.RadioButton("searchBy", "StaffName", true)<text>Name</text>
      @Html.TextBox("search") <input type="submit" value="Search"/>
            }
     }
</p>
@*the above was added to search a particular name*@

<div class="btn-group">
    @if (User.IsInRole("Admin"))
    {
       <a href="@Url.Action("CreateVoter", "Voter")" class="btn btn-info "><i class="fa fa-plus"></i>Add Staff </a>
    }
</div>
@*<table class="table table-striped table-bordered table-hover @*table-checkable order-column valign-middle" id="example4>*@
    <table class="table table-striped table-bordered table-hover  order-column valign-middle" id="example4">
        <thead>
            <tr>
                @*@if (User.IsInRole("Admin"))
                {
                <th> s/n </th>
                }*@
                 @if (User.IsInRole("Admin"))
                 {
                <th> Staff Name </th>
                <th> Staff NO. </th>
                <th>Email</th>
                <th> Department </th>
                <th> Date Created </th>
                <th> Action </th>
                }

            </tr>
        </thead>
        <tbody>
            @*this wiil display if nothing is found*@

            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="5">No rows match search creteria</td>
                </tr>
            }
            else
            {

                foreach (var item in Model)
                {
                    if(User.IsInRole("Admin"))
                    { 
            <tr class="gradeX odd" role="row" id="row-@item.VoterId">

                <td>@Html.DisplayFor(modelItem => item.StaffName)</td>
                <td>@Html.DisplayFor(modelItem => item.StaffNo)</td>
                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                <td>@Html.DisplayFor(modelItem => item.Department)</td>
                @if (User.IsInRole("Admin"))
                {
                <td>@String.Format("{0:d}", item.CreatedDate)</td>
                }
                <td>
                    @if (User.IsInRole("Admin"))
                    {
                    <a href="/Voter/EditVoter?id=@item.VoterId" class="btn btn-primary btn-xs">
                        <i class="fa fa-pencil"></i>Edit
                    </a>
                    <a href="#" class="btn btn-danger btn-xs" id="deleteaction" data-id="@item.VoterId" data-name="@item.StaffName">
                        <i class="fa fa-trash-o "></i> Delete
                    </a>
                    }

                </td>
            </tr>
                    }
                }
            }
           

        </tbody>
            
    </table>

@*These codes in section was added to enable log out at everypage*@
@section Script{
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/toastr.js"></script>

    <script type="text/javascript">toastr.success("@(TempData["Message"] as string)");</script>
}




@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
<script>
    $(function () {

        $(document).on('click', '#deleteaction', function (e) {
            e.preventDefault();

            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            var votName = $(this).attr("data-name");
            if (recordToDelete !== '') {
                var confirmValue = confirm("Are you sure you want to delete this Staff Name(s)? ");
                if (confirmValue) {
                  
                    // Perform the ajax post DeleteFaculty(int id, string facultyName)
                    $.post("/Voter/DeleteVoter", { "id": recordToDelete, "votName": votName },
                        function (data) {
                            // Successful requests get here
                            // Update the page elements
                            if (data.status == true) {
                                //$("html").removeClass("loading")
                                $('#row-' + recordToDelete).fadeOut("slow", function () { $(this).remove(); });
                                alert(data.message);
                            }
                            else {
                                $("html").removeClass("loading")
                                alert(data.error);
                            }

                        });

                }
                else {
                   // $("html").removeClass("loading")
                    return;

                }

            }
        });

        });

</script>

Cyber_Kitchen/Views/Voter/UploadVoters.cshtml
@model Cyber_Kitchen.Models.VoterModel

@{
    ViewBag.Title = "Upload Voter Names";

}

<div class="page-content-wrapper">
    @*@Html.Partial("Message")*@
        @*<div class="page-content" style="min-height:1603px">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class="pull-left">
                        <div class="page-title">Upload Voter Names</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li>*@
                            @*<i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="index.html">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                        </li>
                        <li>
                            <a class="parent-item" href="#">Student</a>&nbsp;<i class="fa fa-angle-right"></i>
                        </li>*@
                        @*<li class="active">Upload Voter Names</li>
                    </ol>
                </div>
            </div>*@
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="card card-box">
                        <div class="card-head">
                            <header></header>
                            <button id="panel-button" class="mdl-button mdl-js-button mdl-button--icon pull-right" data-upgraded=",MaterialButton">
                                @*<i class="material-icons">more_vert</i>*@
                            </button>

                        </div>
    <div class="card-body" id="bar-parent">
        <form action="UploadVoters" method="Post" id="form_sample_1" class="form-horizontal" @*novalidate="novalidate"*@ enctype="multipart/form-data">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-body"> 
                @*<div class="form-group row">
                   All 
                    <span class="required" aria-required="true"> * </span>
                </div>*@

                <div class="form-actions">
                    <div class="row">                        
                        <div class="offset-md-3 col-md-3">
                            <input type="file" accept="application/vnd.ms-excel" name="file" id="file" />
                            <button type="submit" class="btn btn-info" id="submitData">Upload</button>
                        </div>
                        <div class="col-md-1">
                            @*<a href="~/DataUploadTemplates/StaffNamesample.xlsx" download="">Download Template</a>*@

                           @Html.ActionLink("Download Template", "DownloadStaffTemplate", "Voter")
            
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
            </div>
        </div>
    @*</div>*@


@section Script{
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/toastr.js"></script>

    <script type="text/javascript">toastr.success("@(TempData["Message"] as string)");</script>
}